### ISSUE TITLE
mysql删除后在linux上手动安装成功。boost换成最新的1_67_0无法成功，过程如下

### ISSUE THREAD

**Issue by zhangshoug** [fasiondog/hikyuu#9]
$ cat Install_hikyuu_on_Linux 
linux mint 18.3 64bit，默认中文安装系统上通过。boost换成最新的1_67_0无法成功
sudo apt-get install vim git bzip2 build-essential autotools-dev automake autoconf

sudo apt-get install hdf5-helpers libhdf5-cpp-11 libhdf5-dev libhdf5-10 libhdf5-serial-dev
sudo apt-get install libmysqlclient-dev libmysqlclient20 libmysql++-dev  libsqlite3-dev libbz2-dev 
下面语句可选.
sudo apt-get install libboost-all-dev liblog4cplus-dev gccxml python3-dev liblzma-dev

tar zxvf ta-lib-0.4.0-src.tar.gz 
cd ta-lib/
./configure --prefix=/usr
make
sudo make install

chmod +x Anaconda3-5.2.0-Linux-x86_64.sh
./Anaconda3-5.2.0-Linux-x86_64.sh
安装完成后关闭终端，再打开。
conda config --add channels 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/'
conda config --add channels 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/'
conda config --set show_channel_urls yes

#conda install -y libgcc 
#conda install -y pandas numpy flask beautifulsoup4 requests ipython
#conda install -y matplotlib lxml hdf5 jupyter
#conda install -y mkl
#conda install -y mysql-python
#conda create --name hiyuu python=3.6
#pip install mysql-connector-python -i https://pypi.tuna.tsinghua.edu.cn/simple

pip install ta-lib -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install pyperclip -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install pyecharts -i https://pypi.tuna.tsinghua.edu.cn/simple

export CPLUS_INCLUDE_PATH=/home/zhangshoug/anaconda3/include/python3.6m/

tar zxvf boost_1_64_0.tar.gz
cd boost_1_64_0/
./bootstrap.sh --exec-prefix=/usr/local
./b2 -q -j 4 threading=multi
根据提示
export BOOST_ROOT=/home/zhangshoug/boost_1_64_0
export BOOST_LIB=/home/zhangshoug/boost_1_64_0//stage/lib
sudo ./b2 install threading=multi

tar zxvf log4cplus-1.2.1.tar.gz 
cd log4cplus-1.2.1/
./configure --prefix=/usr/local CXXFLAGS=-std=c++0x
make -j 4
sudo make install

export LD_RUN_PATH="/usr/local/lib:$LD_RUN_PATH"
export PYTHONPATH=/home/zhangshoug/hikyuu/tools:/home/zhangshoug/anaconda3/
export HIKYUU=/home/zhangshoug/hikyuu
export LD_LIBRARY_PATH=./:/usr/local/lib:/usr/lib:/home/zhangshoug/hikyuu/tools/hikyuu/
export CPLUS_INCLUDE_PATH=/home/zhangshoug/anaconda3/include/python3.6m/::/home/zhangshoug/hikyuu/extern-libs/sqlite3/:/home/zhangshoug/hikyuu/extern-libs/mysql/:/usr/include/:/usr/include/hdf5/serial/:/usr/local/include/log4cplus/

git clone https://github.com/fasiondog/hikyuu.git
cd hikyuu/
如出现mysql相关错误。
zhangshoug@zhangshouguo-VirtualBox ~ $ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hikyuu.interactive.interactive import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangshoug/hikyuu/tools/hikyuu/__init__.py", line 56, in <module>
    from .core import *
  File "/home/zhangshoug/hikyuu/tools/hikyuu/core.py", line 34, in <module>
    from .core_doc import *
  File "/home/zhangshoug/hikyuu/tools/hikyuu/core_doc.py", line 28, in <module>
    from hikyuu._hikyuu import *
ImportError: /home/zhangshoug/hikyuu/tools/hikyuu/libhikyuu.so: undefined symbol: mysql_num_rows
则如下操作:
find ./ -name mysql|xargs rm -rf
find ./ -type f -name '*.cpp'|xargs grep 'mysql'
find ./ -type f -name '*.cpp'|xargs grep 'MySQL'
修改cpp,删除mysql相关语句。

cp Jamroot.linux Jamroot.linux.orig
vi +13 Jamroot.linux
改成如下:你的python版本和python安装目录
using python : 3.6 : : /home/zhangshoug/anaconda3 ;

./build.sh
如遇错误：
cd tools/hikyuu/
python hku_config.py 
./importdata 
再返回运行
./build.sh

 $ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hikyuu.interactive.interactive import *
21:13:17 TRACE - SQLITE3: /home/zhangshoug/stock/stock.db
21:13:17 TRACE - Loading market information...
21:13:17 TRACE - Loading stock type information...
21:13:17 TRACE - Loading stock information...
21:13:17 TRACE - Loading KData...
21:13:17 TRACE - Preload all day kdata to buffer! [StockManager::setKDataDriver]
21:13:18 TRACE - 1.6755 seconds Loaded Data.
>>> exit()
21:13:22 TRACE - Closed Sqlite3 database!
21:13:22 TRACE - Quit Hikyuu system!
安装完成后将如下语句加入.bashrc
export PATH="/home/zhangshoug/hikyuu/tools/hikyuu:$PATH"

**Comment by jingmouren** [comment]
我装了boost，设置了boost_ROOT和LIB后
再运行xmake
出现如下错误
[ 21%]: ccache compiling.release hikyuu_pywrap/trade_sys/_Condition.cpp
error: /home/.../github/boost_1_71_0/boost/python/detail/caller.hpp:191:5: error: mangled name for 'boost::python::detail::caller<F, CallPolicies, Sig>::caller(F, CallPolicies) [with F = long unsigned int (std::vector<std::shared_ptr<hku::System> >::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Sig = boost::mpl::vector2<long unsigned int, std::vector<std::shared_ptr<hku::System> >&>]' will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
     caller(F f, CallPolicies p) : base(f,p) {}
     ^~~~~~
/home/.../github/boost_1_71_0/boost/python/detail/caller.hpp:191:5: error: mangled name for 'boost::python::detail::caller<F, CallPolicies, Sig>::caller(F, CallPolicies) [with F = long unsigned int (std::vector<std::shared_ptr<hku::System> >::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Sig = boost::mpl::vector2<long unsigned int, std::vector<std::shared_ptr<hku::System> >&>]' will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
In file included from /home/.../github/boost_1_71_0/boost/python/object/function_handle.hpp:10:0,
                 from /home/.../github/boost_1_71_0/boost/python/converter/arg_to_python.hpp:19,
                 from /home/.../github/boost_1_71_0/boost/python/call.hpp:15,
                 from /home/.../github/boost_1_71_0/boost/python/object_core.hpp:14,
                 from /home/.../github/boost_1_71_0/boost/python/args.hpp:22,
                 from /home/.../github/boost_1_71_0/boost/python.hpp:11,
                 from hikyuu_pywrap/trade_sys/_System.cpp:8:
/home/.../github/boost_1_71_0/boost/python/object/py_function.hpp: In instantiation of 'boost::python::objects::py_function::py_function(const Caller&) [with Caller = boost::python::detail::caller<long unsigned int (std::vector<std::shared_ptr<hku::System> >::*)() const noexcept, boost::python::default_call_policies, boost::mpl::vector2<long unsigned int, std::vector<std::shared_ptr<hku::System> >&> >]':
/home/.../github/boost_1_71_0/boost/python/make_function.hpp:60:38:   required from 'boost::python::api::object boost::python::detail::make_function_aux(F, const CallPolicies&, const Sig&, const keyword_range&, NumKeywords) [with F = long unsigned int (std::vector<std::shared_ptr<hku::System> >::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Sig = boost::mpl::vector2<long unsigned int, std::vector<std::shared_ptr<hku::System> >&>; NumKeywords = mpl_::int_<0>; boost::python::detail::keyword_range = std::pair<const boost::python::detail::keyword*, const boost::python::detail::keyword*>]'
/home/.../github/boost_1_71_0/boost/python/make_function.hpp:140:37:   required from 'boost::python::api::object boost::python::make_function(F, const CallPolicies&, const Keywords&, const Signature&) [with F = long unsigned int (std::vector<std::shared_ptr<hku::System> >::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Keywords = boost::python::detail::keywords<0>; Signature = boost::mpl::vector2<long unsigned int, std::vector<std::shared_ptr<hku::System> >&>]'
/home/.../github/boost_1_71_0/boost/python/class.hpp:493:26:   required from 'void boost::python::class_<T, X1, X2, X3>::def_impl(T*, const char*, Fn, const Helper&, ...) [with T = std::vector<std::shared_ptr<hku::System> >; Fn = long unsigned int (std::vector<std::shared_ptr<hku::System> >::*)() const noexcept; Helper = boost::python::detail::def_helper<const char*>; W = std::vector<std::shared_ptr<hku::System> >; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]'
/home/.../github/boost_1_71_0/boost/python/class.hpp:231:9:   required from 'boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const char*, F) [with F = long unsigned int (std::vector<std::shared_ptr<hku::System> >::*)() const noexcept; W = std::vector<std::shared_ptr<hku::System> >; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified; boost::python::class_<T, X1, X2, X3>::self = boost::python::class_<std::vector<std::shared_ptr<hku::System> > >]'
hikyuu_pywrap/trade_sys/_System.cpp:63:43:   required from here

**Comment by fasiondog** [comment]
根目录下的xmake. lua里把set_warning一行注释掉就行
